### ISSUE TITLE
v1.3.0 and vcpkg

### ISSUE THREAD

**Issue by Rasmus-123** [sonodima/wmipp#2]
Hi,

v1.2.0 has some issues with ```object.GetProperty<std::vector<std::string>>``` that are resolved with the current state of the repository.  

The vcpkg version however is still on the last official release and not the updated state.  

Would it be possible for you to create a new v1.3.0 release at the current state of main and update it in vcpkg?  
I could do the latter aswell, I'd just need a new release to update the port to.

Best Wishes

**Comment by Rasmus-123** [comment]
Thank you :)

I've created a pull request for vcpkg: https://github.com/microsoft/vcpkg/pull/41253

**Comment by sonodima** [comment]
Thanks! I was going to make the PR later today, but you beat me to it :)
